# yaml-language-server: schema=https://raw.githubusercontent.com/canonical/cloud-init/main/cloudinit/config/schemas/versions.schema.cloud-config.json
#cloud-config

# ubuntu tested the following list
# todo test debian distro
packages:
  - apt-file
  - apache2-utils
  - bat
  - command-not-found
  - curl
  - dnsutils
  # - exa # ubuntu 23.10 (yes), debian trixie (no)
  - feh
  - fish
  - fzf
  - git
  - git-lfs
  - grc
  - hey
  - htop
  - icdiff
  - iproute2
  - iputils-arping
  - iputils-ping
  - iputils-tracepath
  - jq
  - lshw
  - lsof
  - net-tools
  - most
  - pipx
  - procps
  - psmisc
  - silversearcher-ag
  - tree
  - tldr
  - unzip
  - util-linux
  - vim
  - wget

runcmd:
  # obviously not re-runnable:
  - git clone https://github.com/g0t4/dotfiles /home/wes/repos/github/g0t4/dotfiles
# subs/dotfiles/fish/install/install.fish
