include:
  - applescript
  - bash
  - fish
  - json
  - lua
  - ps1
  - py
  - rs
  - snippets
  - vim
  - zsh
  # - yaml # not many, yet?
ignores:
  - "notes/"
global_languages:
  - lua
  - py
  - fish
  - bash
  - zsh
  - ps1
  - vim
  # TODO just use all, always?
