include:
  - lua
  - py
  - fish
  - zsh
  - bash
  - json
  - ps1
  - applescript
  - snippets
  - rs
  - vim
  # - yaml # not many, yet?
ignores:
  - "notes/"
all_languages:
  - lua
  - py
  - fish
  - bash
  - zsh
  - ps1
  - vim
  # TODO just use all, always?
