include_domains:
  - applescript
  - bash
  - fish
  - json
  - lua
  - ps1
  - py
  - rs
  - snippets
  - vim
  - zsh
  # - yaml # not many, yet?
ignores:
  - "notes/"
global_domains:
  - bash
  - fish
  - lua
  - ps1
  - py
  - vim
  - zsh
