if not vim.fn.getcwd():match("%.config/hammerspoon$") then
    error("\n\n*** CURRENT DIRECTORY IS NOT INSIDE hammerspoon config, require calls in tests won't work...\n\n\tuse `cd $WES_DOTFILES/.config/hammerspoon && nvim`)\n\n")
end
require("config.tests.setup")
local should = require('devtools.tests.should')
local describe = require('devtools.tests.define.describe')
local only = require('devtools.tests.define.only')
local skip = require('devtools.tests.define.skip')
local log = require("config.logs").launcher()

local casing = require("config.launcher.casing")

describe("sentence_case", function()
    describe("change case", function()
        it("first word is uppercase", function()
            should.be_equal(casing.sentence_case("this is a test"), "This is a test")
        end)
        it("not first word is lowercase", function()
            should.be_equal(casing.sentence_case("The Cat Ran Into A Bus"), "The cat ran into a bus")
        end)
    end)

    describe("as-is", function()
        describe("if all uppercase letters then leave as-is (assume acronym)", function()
            -- I shouldn't need to register all acronyms
            it("first word", function()
                should.be_equal(casing.sentence_case("NASA ran a test"), "NASA ran a test") -- first word
            end)
            it("middle word", function()
                should.be_equal(casing.sentence_case("We had NASA run a test"), "We had NASA run a test") -- middle word
            end)
            it("last word", function()
                should.be_equal(casing.sentence_case("They ran a test with NASA"), "They ran a test with NASA") -- last word
            end)
            it("except single character words like 'A' which should be lowercase", function()
                should.be_equal(casing.sentence_case("This is Not A Test"), "This is not a test")
            end)
            -- TODO am I missing a ton of examples of words that are 2+ chars that I would want lowercase if not first word or explicitly perserved?
            -- TODO or can I generalize to a better rule: if any char after first is capitalized, then leave word as-is?
            --  is there ever a time when a general word would be CamelCase if start of sentence but then pascalCase in middle (or smth else like that if not cameal/pascal word cased)
        end)

        describe("preserve words that are a verbatim match (case sensitive) in preserve_words", function()
            -- keep them exactly as-is if they match exactly
            it("first word", function()
                should.be_equal(casing.sentence_case("VirtualBox is great"), "VirtualBox is great")
            end)
            it("middle word", function()
                should.be_equal(casing.sentence_case("I love VirtualBox daily"), "I love VirtualBox daily")
            end)
            it("last word", function()
                should.be_equal(casing.sentence_case("I love VirtualBox"), "I love VirtualBox")
            end)
        end)

        describe("punctuation", function()
            it("dotted notation", function()
                should.be_equal(casing.sentence_case("I used community.docker.docker_containers module"), "I used community.docker.docker_containers module")
            end)
            -- FYI no multi sentence support for now, I do not need it. Add if and when I need it
            it("exclamation at end is preserved", function()
                should.be_equal(casing.sentence_case("I used a module!"), "I used a module!")
            end)
            it("question at end is preserved", function()
                should.be_equal(casing.sentence_case("What are you talking about?"), "What are you talking about?")
            end)
        end)
    end)

    describe("metadata stripping", function()
        describe("prefix stripping", function()
            it("strips m2-04 prefix", function()
                should.be_equal(casing.sentence_case("m2-04 this is a test"), "This is a test")
            end)
            it("strips M2-04 prefix (uppercase M)", function()
                should.be_equal(casing.sentence_case("M2-04 this is a test"), "This is a test")
            end)
            it("strips m01a10 prefix", function()
                should.be_equal(casing.sentence_case("m01a10 this is a test"), "This is a test")
            end)
            it("strips M2 02 prefix (digit space digit)", function()
                should.be_equal(casing.sentence_case("M2 02 this is a test"), "This is a test")
            end)
            it("strips m2 04 prefix", function()
                should.be_equal(casing.sentence_case("m2 04 this is a test"), "This is a test")
            end)
            it("strips m2-04 followed by DONE prefix", function()
                should.be_equal(casing.sentence_case("m2-04 DONE this is a test"), "This is a test")
            end)
            it("strips M2 02 followed by PERFECT prefix", function()
                should.be_equal(casing.sentence_case("M2 02 PERFECT Tags let you work"), "Tags let you work")
            end)
            it("strips m01a10 followed by FOOBAR prefix", function()
                should.be_equal(casing.sentence_case("m01a10 FOOBAR Tags let you work"), "Tags let you work")
            end)
            it("strips combined M2 02 DONE prefix", function()
                should.be_equal(casing.sentence_case("M2 02 DONE Verify Tags With The   Tags Filter.30fps Aa7cdd4f"), "Verify tags with the   tags filter")
            end)
        end)

        describe("suffix stripping", function()
            it("strips .30fps suffix attached to word", function()
                should.be_equal(casing.sentence_case("this is a checklist.30fps"), "This is a checklist")
            end)
            it("strips .60fps suffix attached to word", function()
                should.be_equal(casing.sentence_case("this is a checklist.60fps"), "This is a checklist")
            end)
            it("strips .mp4 extension", function()
                should.be_equal(casing.sentence_case("this is a test.mp4"), "This is a test")
            end)
            it("strips .MP4 extension (uppercase)", function()
                should.be_equal(casing.sentence_case("this is a test.MP4"), "This is a test")
            end)
            it("strips .mkv extension", function()
                should.be_equal(casing.sentence_case("this is a test.mkv"), "This is a test")
            end)
            it("strips sha256 hash suffix (8+ hex chars)", function()
                should.be_equal(casing.sentence_case("this is a test abc12345678"), "This is a test")
            end)
            it("strips hyphenated sha256 hash suffix", function()
                should.be_equal(casing.sentence_case("this is a test-abc1234567890abcdef"), "This is a test")
            end)
            it("strips sha256 hash suffix with mixed case hex", function()
                should.be_equal(casing.sentence_case("this is a test Aa7cdd4f"), "This is a test")
            end)
            it("strips hyphenated sha256 hash suffix before .mp4 extension", function()
                should.be_equal(casing.sentence_case("this is a test-abc12345678.mp4"), "This is a test")
            end)
        end)

        describe("combined prefix and suffix stripping", function()
            it("strips m2-04 prefix and .mp4 suffix with hash", function()
                should.be_equal(casing.sentence_case("m2-04 this is a test abc123456789.mp4"), "This is a test")
            end)
            it("strips EDITED prefix and .30fps suffix", function()
                should.be_equal(casing.sentence_case("EDITED this is a test .30fps"), "This is a test")
            end)
            it("full scenario: M2 02 DONE Verify Tags With The   Tags Filter.30fps Aa7cdd4f with trailing space", function()
                should.be_equal(casing.sentence_case("M2 02 DONE Verify Tags With The   Tags Filter.30fps Aa7cdd4f "), "Verify tags with the   tags filter")
            end)
            it("scenario: m2-06 DONE Tags let you work through tasks like a checklist.30fps 91e06127 .mp4", function()
                should.be_equal(casing.sentence_case("m2-06 DONE Tags let you work through tasks like a checklist.30fps 91e06127 .mp4"), "Tags let you work through tasks like a checklist")
            end)
        end)
    end)
end)
