"""Generated from fish/load_last_interactive_only/docker-specific.fish."""

from __future__ import annotations

from wes_abbreviations import abbr


def register_docker_abbreviations():
    abbr('din', 'docker inspect')
    abbr('dmo', 'docker model')
    abbr('dmols', 'docker model list')
    abbr('dmoi', 'docker model inspect')
    abbr('dmol', 'docker model logs')
    abbr('dmopull', 'docker model pull')
    abbr('dmopush', 'docker model push')
    abbr('dmor', 'docker model run')
    abbr('dmorm', 'docker model rm')
    abbr('dmot', 'docker model tag')
    abbr('dmost', 'docker model status')
    abbr('dmov', 'docker model version')
    abbr('dst', 'docker stack')
    abbr('dstd', 'docker stack deploy -c')
    abbr('dstls', 'docker stack ls')
    abbr('dstps', 'docker stack ps')
    abbr('dstrm', 'docker stack rm')
    abbr('dsts', 'docker stack services')
    abbr('dse', 'docker service')
    abbr('dsec', 'docker service create')
    abbr('dsei', 'docker service inspect')
    abbr('dsel', 'docker service logs')
    abbr('dsels', 'docker service ls')
    abbr('dseps', 'docker service ps')
    abbr('dserm', 'docker service rm')
    abbr('dserb', 'docker service rollback')
    abbr('dses', 'docker service scale')
    abbr('dseu', 'docker service update')
    abbr('dseuf', 'docker service update --force')
    abbr('dsw', 'docker swarm')
    abbr('dswi', 'docker swarm init')
    abbr('dswj', 'docker swarm join')
    abbr('dswjt', 'docker swarm join-token')
    abbr('dswl', 'docker swarm leave')
    abbr('dno', 'docker node')
    abbr('dnoi', 'docker node inspect')
    abbr('dnols', 'docker node ls')
    abbr('dnops', 'docker node ps')
    abbr('dnorm', 'docker node rm')
    abbr('dnou', 'docker node update')
    abbr('dnopr', 'docker node promote')
    abbr('dnode', 'docker node demote')
    abbr('dcfg', 'docker config')
    abbr('dcfgc', 'docker config create')
    abbr('dcfgi', 'docker config inspect')
    abbr('dcfgls', 'docker config ls')
    abbr('dcfgrm', 'docker config rm')
    abbr('dsrt', 'docker secret')
    abbr('dsrtc', 'docker secret create')
    abbr('dsrti', 'docker secret inspect')
    abbr('dsrtls', 'docker secret ls')
    abbr('dsrtrm', 'docker secret rm')
    abbr('dsy', 'docker system')
    abbr('dsydf', 'docker system df')
    abbr('dsydfv', 'docker system df -v')
    abbr('dsyi', 'docker system info')
    abbr('dsypr', 'docker system prune')
    abbr('dsye_tr_table', 'docker system events --since 10m --until 0m --format "{{json .}}" | jq "[( .id[0:10] // .Actor.ID ),.Type, .Action] | @csv " -r | column -t -s","  ')
    abbr('dv', 'docker volume')
    abbr('dvls', 'docker volume ls')
    abbr('dvlsd', 'docker volume ls -f=dangling=true')
    abbr('dvc', 'docker volume create')
    abbr('dvrm', 'docker volume rm')
    abbr('dvpr', 'docker volume prune')
    abbr('dvi', 'docker volume inspect')
    abbr('dver', 'docker version')
    abbr('dc', 'docker container')
    abbr('dca', 'docker container attach')
    abbr('dcc', 'docker container commit')
    abbr('dccp', 'docker container cp')
    abbr('dccreate', 'docker container create')
    abbr('dcd', 'docker container diff')
    abbr('dce', 'docker container exec -i -t ')
    abbr('dcexport', 'docker container export')
    abbr('dci', 'docker container inspect')
    abbr('dck', 'docker container kill')
    abbr('dcl', 'docker container logs')
    abbr('dcpause', 'docker container pause')
    abbr('dcport', 'docker container port')
    abbr('dcpr', 'docker container prune')
    abbr('dcps', 'docker container ps')
    abbr('dcpsa', 'docker container ps -a')
    abbr('dcpsm', 'docker container ps --format "table {{.ID}}\\t{{.Names}}\\t{{.Image}}\\t{{.Mounts}}"')
    abbr('dcr', 'docker container run --name')
    abbr('dcrename', 'docker container rename')
    abbr('dcrestart', 'docker container restart')
    abbr('dcri', 'docker container run -i -t --rm ')
    abbr('dcrie', 'docker container run -i -t --rm --entrypoint ')
    abbr('dcrpriv', 'docker container run -i -t --rm --privileged --pid host ubuntu nsenter -t 1 -a')
    abbr('dcrm', 'docker container rm -f')
    abbr('dcstart', 'docker container start')
    abbr('dcstats', 'docker container stats')
    abbr('dcstop', 'docker container stop')
    abbr('dct', 'docker container top')
    abbr('dcunpause', 'docker container unpause')
    abbr('dcupdate', 'docker container update')
    abbr('dcwait', 'docker container wait')
    abbr('di', 'docker image')
    abbr('dbx', 'docker buildx')
    abbr('dbxls', 'docker buildx ls')
    abbr('dbxb', 'docker buildx build')
    abbr('dbxba', 'docker buildx bake')
    abbr('dbxc', 'docker buildx create')
    abbr('dbxrm', 'docker buildx rm')
    abbr('dbxdu', 'docker buildx du')
    abbr('dbxi', 'docker buildx inspect')
    abbr('dbxpr', 'docker buildx prune')
    abbr('dbxst', 'docker buildx stop')
    abbr('dbxu', 'docker buildx use')
    abbr('dbxv', 'docker buildx version')
    abbr('dbxit', 'docker buildx imagetools')
    abbr('dib', 'docker image build')
    abbr('dih', 'docker image history --no-trunc')
    abbr('dihj', 'docker image history --no-trunc --format "{{json .}}" | jq')
    abbr('dii', 'docker image inspect')
    abbr('dils', 'docker image ls')
    abbr('dilsa', 'docker image ls --all')
    abbr('dilsj', 'docker image ls --format "{{json .}}" | jq')
    abbr('dilsaj', 'docker image ls --all --format "{{json .}}" | jq')
    abbr('dilsdf', "docker image ls --format '{{.Size}}\\t{{.Repository}}:{{.Tag}}' | sort -h")
    abbr('dipr', 'docker image prune')
    abbr('dipull', 'docker image pull')
    abbr('dipush', 'docker image push')
    abbr('dirm', 'docker image rm')
    abbr('dit', 'docker image tag')
    abbr('dm', 'docker manifest')
    abbr('dmi', 'docker manifest inspect')
    abbr('dne', 'docker network')
    abbr('dnec', 'docker network connect')
    abbr('dned', 'docker network disconnect')
    abbr('dnei', 'docker network inspect')
    abbr('dnels', 'docker network ls')
    abbr('dnepr', 'docker network prune')
    abbr('dnerm', 'docker network rm')
    abbr('dx', 'docker context')
    abbr('dxls', 'docker context ls')
    abbr('dxu', 'docker context use')
    abbr('dxud', 'docker context use default')
    abbr('dxi', 'docker context inspect')
    abbr('dxc', 'docker context create')
    abbr('dxrm', 'docker context rm')
    abbr('dxs', 'docker context show')
    abbr('dco', 'docker compose')
    abbr('dcob', 'docker compose build --pull')
    abbr('dcoc', 'docker compose config')
    abbr('dcocp', 'docker compose cp')
    abbr('dcod', 'docker compose down --remove-orphans')
    abbr('dcodd', 'docker compose down --remove-orphans --dry-run')
    abbr('dcoda', 'docker compose down --remove-orphans --rmi local --volumes')
    abbr('dcodad', 'docker compose down --remove-orphans --rmi local --volumes --dry-run')
    abbr('dcoe', 'docker compose exec')
    abbr('dcoa', 'docker compose attach')
    abbr('dcow', 'docker compose watch')
    abbr('dcoi', 'docker compose images')
    abbr('dcok', 'docker compose kill')
    abbr('dcol', 'docker compose logs')
    abbr('dcolf', 'docker compose logs -f')
    abbr('dcolt', 'docker compose logs -f --tail=0')
    abbr('dcops', 'docker compose ps')
    abbr('dcopsa', 'docker compose ps -a')
    abbr('dcols', 'docker compose ls')
    abbr('dcolsa', 'docker compose ls -a')
    abbr('dcopull', 'docker compose pull')
    abbr('dcopush', 'docker compose push')
    abbr('dcorm', 'docker compose rm')
    abbr('dcor', 'docker compose run --rm')
    abbr('dcorb', 'docker compose run --rm --build')
    abbr('dcore', 'docker compose restart')
    abbr('dcostart', 'docker compose start')
    abbr('dcostop', 'docker compose stop')
    abbr('dcot', 'docker compose top')
    abbr('dcou', 'docker compose up')
    abbr('dcoub', 'docker compose up --build')
    abbr('dcouf', 'docker compose up --build --force-recreate --remove-orphans')
    abbr('dcoud', 'docker compose up --detach')
    abbr('dcouw', 'docker compose up --watch')
    abbr('dcov', 'docker compose version')
    abbr('dd', 'docker debug')
    abbr('ddc', "docker debug --command '%'", cursor_marker="%")
    abbr('dde', 'docker debug -c entrypoint')
    abbr('sk', 'skopeo')
    abbr('skh', 'skopeo --help')
    abbr('ski', 'skopeo --override-os linux inspect docker://%', cursor_marker="%")
    abbr('skim', 'skopeo --override-os linux inspect --raw docker://%', cursor_marker="%")
    abbr('skic', 'skopeo --override-os linux inspect --config --raw docker://%', cursor_marker="%")
    abbr('skl', 'skopeo list-tags docker://docker.io/%', cursor_marker="%")
    abbr('sklm', 'skopeo list-tags docker://mcr.microsoft.com/%', cursor_marker="%")
    abbr('dh', 'hub-tool')
    abbr('dhr', 'hub-tool repo ls')
    abbr('dht', 'hub-tool tag ls --sort=name=desc --platforms --all')
    abbr('dhtu', 'hub-tool tag ls --sort=updated=desc --platforms --all')
    abbr('dhtj', 'hub-tool tag ls --format json % | jq', cursor_marker="%")
    abbr('dhti', 'hub-tool tag inspect')
