"""generated from Fish"""

from __future__ import annotations

from wes_abbreviations import abbr


FISH_FUNCTIONS = (
    'on_change_show_verbose_prompt',
    'toggle_show_verbose_prompt',
)


def register_wes_system_services_abbreviations():
    abbr('help', 'help_online')
    abbr('lcl', 'launchctl list')
    abbr('lcp', 'launchctl print system')
    abbr('lcpu', 'launchctl print user/$(id -u)')
    abbr('lcpg', 'launchctl print gui/$(id -u)')
    abbr('lcds', 'launchctl disable system/')
    abbr('lcdu', 'launchctl disable user/$(id -u)')
    abbr('lcdg', 'launchctl disable gui/$(id -u)')
    abbr('lcstart', 'launchctl start TODO')
    abbr('lcstop', 'launchctl stop TODO')
    abbr('lcrm', 'launchctl remove TODO')
    abbr('lcexamine', 'launchctl examine TODO')
    abbr('sc', 'sudo systemctl')
    abbr('scu', 'systemctl --user')
    abbr('scudr', 'systemctl --user daemon-reload')
    abbr('scdr', 'sudo systemctl daemon-reload')
    abbr('scm', 'man systemd.index')
    abbr('scs', 'sudo systemctl status')
    abbr('scus', 'systemctl --user status')
    abbr('scstop', 'sudo systemctl stop')
    abbr('scustop', 'systemctl --user stop')
    abbr('scstart', 'sudo systemctl start')
    abbr('scustart', 'systemctl --user start')
    abbr('screstart', 'sudo systemctl restart')
    abbr('scurestart', 'systemctl --user restart')
    abbr('scenable', 'sudo systemctl enable')
    abbr('scuenable', 'systemctl --user enable')
    abbr('scdisable', 'sudo systemctl disable')
    abbr('scudisable', 'systemctl --user disable')
    abbr('sck', 'sudo systemctl kill')
    abbr('scukill', 'systemctl --user kill')
    abbr('sccat', 'sudo systemctl cat')
    abbr('scucat', 'systemctl --user cat')
    abbr('scedit', 'sudo systemctl edit')
    abbr('scuedit', 'systemctl --user edit')
    abbr('screvert', 'sudo systemctl revert')
    abbr('scurevert', 'systemctl --user revert')
    abbr('scshow', 'sudo systemctl show')
    abbr('scushow', 'systemctl --user show')
    abbr('scls', 'sudo systemctl list-units')
    abbr('sculs', 'systemctl --user list-units')
    abbr('sclsf', 'sudo systemctl list-unit-files')
    abbr('sculsf', 'systemctl --user list-unit-files')
    abbr('sclss', 'sudo systemctl list-sockets')
    abbr('sculss', 'systemctl --user list-sockets')
    abbr('sclsd', 'sudo systemctl list-dependencies')
    abbr('sculsd', 'systemctl --user list-dependencies')
    abbr('jc', 'sudo journalctl --unit')
    abbr('jcu', 'journalctl --user --unit')
    abbr('jcb', 'sudo journalctl --boot --unit')
    abbr('jcub', 'journalctl --user --boot --unit')
    abbr('jcb1', 'sudo journalctl --boot=-1 --unit')
    abbr('jcub1', 'journalctl --user --boot=-1 --unit')
    abbr('jcboots', 'sudo journalctl --list-boots')
    abbr('jcs', 'sudo journalctl --since "1min ago" --unit')
    abbr('jcus', 'journactl --user --since "1min ago" --unit')
    abbr('jck', 'sudo journalctl -k')
    abbr('jcuk', 'journalctl --user -k')
    abbr('jcf', 'sudo journalctl --follow --unit')
    abbr('jcuf', 'journalctl --user --follow --unit')
    abbr('jcfa', 'sudo journalctl --follow --no-tail --unit')
    abbr('jcufa', 'journalctl --user --follow --no-tail --unit')
    abbr('jc_rotate_vaccum', 'sudo journalctl --rotate --vacuum-time=1s')
    abbr('jc_nuke', 'sudo journalctl --rotate --vacuum-time=1s')
    abbr('jc_rotate_only', 'sudo journalctl --rotate')
    abbr('jcvs', 'sudo journalctl --vacuum-size=100M')
    abbr('jcdu', 'sudo journalctl --disk-usage')
    abbr('jcud', 'journalctl --user --disk-usage')
    abbr('ctr', 'sudo ctr')
    abbr('ctrn', 'sudo ctr namespaces ls')
    abbr('ctrc', 'sudo ctr container ls')
    abbr('ctrci', 'sudo ctr container info')
    abbr('ctrcrm', 'sudo ctr container rm')
    abbr('ctri', 'sudo ctr image ls')
    abbr('ctripull', 'sudo ctr image pull docker.io/library/%', cursor_marker="%")
    abbr('ctrirm', 'sudo ctr image rm docker.io/library/%', cursor_marker="%")
    abbr('ctrtls', 'sudo ctr task ls')
    abbr('ctrtps', 'sudo ctr task ps')
    abbr('ctrta', 'sudo ctr task attach')
    abbr('ctrtrm', 'sudo ctr task rm')
    abbr('ctrtk', 'sudo ctr task kill --all')
    abbr('ctrtks', 'sudo ctr task kill --all --signal=SIGKILL')
    abbr('ctrtpause', 'sudo ctr task pause')
    abbr('ctrtresume', 'sudo ctr task resume')
    abbr('ctrtstart', 'sudo ctr task start')
    abbr('ctrtexec', 'sudo ctr task exec --tty --exec-id 100 ')
    abbr('ctrr', 'sudo ctr run -t --rm')
    abbr('ctrrnd', 'sudo ctr run -d docker.io/library/nginx:latest web')
    abbr('ctrrn', 'sudo ctr run -t --rm --net-host docker.io/library/nginx:latest web')
    abbr('containerdc', 'containerd config dump | bat -l toml')
    abbr('containerdcdefault', 'containerd config default | bat -l toml')
