"""Generated from fish/load_last_interactive_only/audio-vido-specific.fish; edit Fish/Zsh and rerun the generator."""

from wes_abbreviations import abbr
from wes_daily_tool_bridges import audio_abbreviation

SOURCE_FUNCTIONS = ('_exiftool_et', '_exiftool_etc', '_exiftool_ets', 'ffmpeg', 'ffprobe', 'ffplay', '_create_abbr_ff_help_filter', '_ff_volumedetect', '_ff_wav', '_ff_silencedetect', '_ff_astats', '_ff_astats_per_frame', '_ff_astats_overall', '_ff_astats_perchannel', '_ffprobe_expand_cmd', '_ffpshow_chapters', '_ffpshow_packets_video', '_ffpshow_packets_audio', '_ffpshow_streams', '_ffpshow_stream_groups', '_ffpshow_frames_video', '_ffpshow_frames_audio', '_ffpshow_format', '_ffpcount_frames', '_ffpcount_packets', '_ffpcount_both')


def register_audio_video_abbreviations():
    abbr('et', audio_abbreviation('_exiftool_et', cursor=False))
    abbr('etc', audio_abbreviation('_exiftool_etc', cursor=False))
    abbr('ets', audio_abbreviation('_exiftool_ets', cursor=False))
    abbr('ff', 'ffmpeg')
    abbr('ffm', 'ffmpeg')
    abbr('ff_help_full', 'ffmpeg -h full')
    abbr('ff_help_encoder', 'ffmpeg -h encoder=')
    abbr('ff_help_decoder', 'ffmpeg -h decoder=')
    abbr('ff_help_muxer', 'ffmpeg -h muxer=')
    abbr('ff_help_demuxer', 'ffmpeg -h demuxer=')
    abbr('ff_help_filter', 'ffmpeg -h filter=')
    abbr('ff_help_protocol', 'ffmpeg -h protocol=')
    abbr('no_output', '-f null -', position="anywhere", commands=('ffmpeg',))
    abbr('ffp', 'ffprobe')
    abbr('ffph', 'ffprobe -h full')
    abbr('ffpshow', 'ffprobe -loglevel warning  -show_%', cursor_marker="%")
    abbr('ff_help_filter_audio_acompressor', 'ffmpeg --help filter=acompressor && open https://ffmpeg.org/ffmpeg-filters.html#acompressor')
    abbr('ff_help_filter_audio_aecho', 'ffmpeg --help filter=aecho && open https://ffmpeg.org/ffmpeg-filters.html#aecho')
    abbr('ff_help_filter_audio_afftdn', 'ffmpeg --help filter=afftdn && open https://ffmpeg.org/ffmpeg-filters.html#afftdn')
    abbr('ff_help_filter_audio_aformat', 'ffmpeg --help filter=aformat && open https://ffmpeg.org/ffmpeg-filters.html#aformat')
    abbr('ff_help_filter_audio_aresample', 'ffmpeg --help filter=aresample && open https://ffmpeg.org/ffmpeg-filters.html#aresample')
    abbr('ff_help_filter_audio_astats', 'ffmpeg --help filter=astats && open https://ffmpeg.org/ffmpeg-filters.html#astats')
    abbr('ff_help_filter_audio_loudnorm', 'ffmpeg --help filter=loudnorm && open https://ffmpeg.org/ffmpeg-filters.html#loudnorm')
    abbr('ff_help_filter_audio_silencedetect', 'ffmpeg --help filter=silencedetect && open https://ffmpeg.org/ffmpeg-filters.html#silencedetect')
    abbr('ff_help_filter_audio_volumedetect', 'ffmpeg --help filter=volumedetect && open https://ffmpeg.org/ffmpeg-filters.html#volumedetect')
    abbr('ff_help_filter_video_crop', 'ffmpeg --help filter=crop && open https://ffmpeg.org/ffmpeg-filters.html#crop')
    abbr('ff_help_filter_video_drawtext', 'ffmpeg --help filter=drawtext && open https://ffmpeg.org/ffmpeg-filters.html#drawtext')
    abbr('ff_help_filter_video_fps', 'ffmpeg --help filter=fps && open https://ffmpeg.org/ffmpeg-filters.html#fps')
    abbr('ff_help_filter_video_hflip', 'ffmpeg --help filter=hflip && open https://ffmpeg.org/ffmpeg-filters.html#hflip')
    abbr('ff_help_filter_video_overlay', 'ffmpeg --help filter=overlay && open https://ffmpeg.org/ffmpeg-filters.html#overlay')
    abbr('ff_help_filter_video_scale', 'ffmpeg --help filter=scale && open https://ffmpeg.org/ffmpeg-filters.html#scale')
    abbr('ff_help_filter_video_transpose', 'ffmpeg --help filter=transpose && open https://ffmpeg.org/ffmpeg-filters.html#transpose')
    abbr('ff_help_filter_video_vflip', 'ffmpeg --help filter=vflip && open https://ffmpeg.org/ffmpeg-filters.html#vflip')
    abbr('ff_help_filter_video_whisper', 'ffmpeg --help filter=whisper && open https://ffmpeg.org/ffmpeg-filters.html#whisper')
    abbr('ff_volumedetect', audio_abbreviation('_ff_volumedetect', cursor=True))
    abbr('ff_wav', audio_abbreviation('_ff_wav', cursor=True))
    abbr('ff_silencedetect', audio_abbreviation('_ff_silencedetect', cursor=True))
    abbr('ff_astats', audio_abbreviation('_ff_astats', cursor=True))
    abbr('ff_astats_per_frame', audio_abbreviation('_ff_astats_per_frame', cursor=True))
    abbr('ff_astats_overall', audio_abbreviation('_ff_astats_overall', cursor=True))
    abbr('ff_astats_perchannel', audio_abbreviation('_ff_astats_perchannel', cursor=True))
    abbr('ffpshow_chapters', audio_abbreviation('_ffpshow_chapters', cursor=True))
    abbr('ffpshow_packets_video', audio_abbreviation('_ffpshow_packets_video', cursor=True))
    abbr('ffpshow_packets_audio', audio_abbreviation('_ffpshow_packets_audio', cursor=True))
    abbr('ffpshow_streams', audio_abbreviation('_ffpshow_streams', cursor=True))
    abbr('ffpshow_stream_groups', audio_abbreviation('_ffpshow_stream_groups', cursor=True))
    abbr('ffpshow_frames_video', audio_abbreviation('_ffpshow_frames_video', cursor=True))
    abbr('ffpshow_frames_audio', audio_abbreviation('_ffpshow_frames_audio', cursor=True))
    abbr('ffpshow_format', audio_abbreviation('_ffpshow_format', cursor=True))
    abbr('ffpcount_frames', audio_abbreviation('_ffpcount_frames', cursor=True))
    abbr('ffpcount_packets', audio_abbreviation('_ffpcount_packets', cursor=True))
    abbr('ffpcount_both', audio_abbreviation('_ffpcount_both', cursor=True))
    abbr('ffpshow_pixel_formats', 'ffprobe -loglevel warning  -show_pixel_formats')
    abbr('ffpshow_version', 'ffprobe -loglevel warning  -show_program_version')
    abbr('ffpl', 'ffplay')
    abbr('ffplh', 'ffplay -h full')
    abbr('sipsg', 'sips -g all')
    abbr('sipsm', "sips --matchTo '/System/Library/ColorSync/Profiles/sRGB Profile.icc' -o new_image_file ")
    abbr('sipsx', 'sips -x profile_extracted_here')
    abbr('sipsf', 'sips --formats')
