"""generated from Fish"""

from __future__ import annotations

import platform
from xonsh.built_ins import XSH
import re

from wes_abbreviations import abbr
from wes_fish_migration import (
    abbr_from_fish_function,
    platform_abbreviation,
    wrap_fish_functions,
)


MAN_COMMAND = "gman" if platform.system() == "Darwin" else "man"

FISH_FUNCTIONS = (
    'dpkg_L_files',
    'dpkg_L_tree',
    'treeify',
    'watch',
    'viddy',
    '_expand_watch_last',
    'wordcount',
    'yq_diff_docs',
    'tellme_about',
    '_indent',
    'npm_install',
    'npx',
    'bitmaths',
    'pretty_size',
    'manlistX',
    'show_hex_rgb_color',
    'treeify_with_icons',
    '__pactree_depth',
    'trash',
    '_fish_from_source',
)


def register_wes_packages_hardware_abbreviations():
    wrap_fish_functions(XSH.aliases, FISH_FUNCTIONS)
    abbr('apts', 'apt search')
    abbr('apti', 'sudo apt install')
    abbr('aptu', 'sudo apt update')
    abbr('aptug', 'sudo apt upgrade')
    abbr('aptl', 'apt list --installed')
    abbr('aptlu', 'apt list --upgradable')
    abbr('aptcm', 'apt-cache madison')
    abbr('dpkgL', 'dpkg -L')
    abbr('dpkgS', 'dpkg -S')
    abbr('watch', '$WATCH_COMMAND')
    abbr('watch_last', abbr_from_fish_function('_expand_watch_last'))
    abbr('wa', '$WATCH_COMMAND')
    abbr('wag', '$WATCH_COMMAND --no-title -- grc --colour=on')
    abbr('wak', '$WATCH_COMMAND --no-title -- grc --colour=on kubectl get --show-kind')
    abbr('wad', '$WATCH_COMMAND --no-title -- grc --colour=on kubectl describe --show-kind')
    abbr('wakp', '$WATCH_COMMAND --no-title -- grc --colour=on kubectl get --show-kind pods')
    abbr('wah', '$WATCH_COMMAND --no-title -- http --pretty=colors')
    abbr('wahv', '$WATCH_COMMAND --no-title -- http --pretty=colors --verbose')
    abbr('wal', '$WATCH_COMMAND --no-title -- grc --colour=on ls')
    abbr('wat', '$WATCH_COMMAND --no-title -- grc --colour=on tree')
    abbr('wc', 'wordcount')
    abbr('pyqi', "| yq eval 'select(documentIndex == 1) | .status'")
    abbr('pyqp', '| yq -P')
    abbr('_reminders_docker_binfmts', 'docker run --privileged --rm tonistiigi/binfmt')
    abbr('npmi', 'npm_install')
    abbr('npminit', 'npm init -y')
    abbr('npml', 'npm list')
    abbr('npmr', 'npm run')
    abbr('npmt', 'npm test')
    abbr('npma', 'npm audit')
    abbr('npmv', 'npm version')
    abbr('npms', 'npm start')
    abbr('npmo', 'npm outdated')
    abbr('npmun', 'npm uninstall')
    abbr('npmup', 'npm update')
    abbr('npxr', 'npx run')
    abbr('ts', 'tree-sitter')
    abbr('tsg', 'tree-sitter generate')
    abbr('tsb', 'tree-sitter build')
    abbr('tsp', 'tree-sitter parse')
    abbr('tst', 'tree-sitter test')
    abbr('tsq', 'tree-sitter query')
    abbr('tsh', 'tree-sitter highlight')
    abbr('tsplayground', 'tree-sitter playground')
    abbr('bm', 'bitmaths')
    abbr('man', 'gman')
    abbr('man_commands_1', '$XONSH_MAN_COMMAND 1')
    abbr('man_syscalls_2', '$XONSH_MAN_COMMAND 2')
    abbr('man_c_stdlib_3', '$XONSH_MAN_COMMAND 3')
    abbr('man_kernel_interfaces_4', '$XONSH_MAN_COMMAND 4')
    abbr('man_file_formats_5', '$XONSH_MAN_COMMAND 5')
    abbr('man_misc_7', '$XONSH_MAN_COMMAND 7')
    abbr('man_system_8', '$XONSH_MAN_COMMAND 8')
    abbr('man_kernel_dev_9', '$XONSH_MAN_COMMAND 9')
    abbr(re.compile('manlist[0-9]'), abbr_from_fish_function('manlistX'))
    abbr('man1', '$XONSH_MAN_COMMAND 1')
    abbr('man2', '$XONSH_MAN_COMMAND 2')
    abbr('man3', '$XONSH_MAN_COMMAND 3')
    abbr('man4', '$XONSH_MAN_COMMAND 4')
    abbr('man5', '$XONSH_MAN_COMMAND 5')
    abbr('man6', '$XONSH_MAN_COMMAND 6')
    abbr('man7', '$XONSH_MAN_COMMAND 7')
    abbr('man8', '$XONSH_MAN_COMMAND 8')
    abbr('man9', '$XONSH_MAN_COMMAND 9')
    abbr('mana', '$XONSH_MAN_COMMAND --all --regex')
    abbr('mank', 'apropos')
    abbr('manf', 'whatis')
    abbr('-K', '--global-apropos', position="anywhere", commands=(MAN_COMMAND,))
    abbr('-k', '--apropos', position="anywhere", commands=(MAN_COMMAND,))
    abbr('-w', '--where', position="anywhere", commands=(MAN_COMMAND,))
    abbr('-a', '--all', position="anywhere", commands=(MAN_COMMAND,))
    abbr('manK', '$XONSH_MAN_COMMAND -K')
    abbr('manw', '$XONSH_MAN_COMMAND --where -K')
    abbr('mgr', '$XONSH_MAN_COMMAND -K')
    abbr('mgrw', '$XONSH_MAN_COMMAND --where -K')
    abbr('manbash', '$XONSH_MAN_COMMAND $HOME/repos/github/g0t4/bash/doc/bash.1')
    abbr('mbash', '$XONSH_MAN_COMMAND $HOME/repos/github/g0t4/bash/doc/bash.1')
    abbr('mitm', 'mitmproxy')
    abbr('mitml', 'mitmproxy --mode=local')
    abbr('mitmw', 'mitmweb')
    abbr('mitmwl', 'mitmweb --mode=local')
    abbr('mitmd', 'mitmdump --mode=local')
    abbr('mitmdl', 'mitmdump --mode=local')
    abbr('mitmr', 'mitmproxy --no-server --rfile')
    abbr('mitm_pgrep', 'pgrep -ilf mitmproxy | rg_grep -v "\\--no-server" || true')
    abbr('mitm_kill', 'pgrep -ilf mitmproxy | rg_grep -v "\\--no-server" | awk \'{print $1}\' | xargs sudo kill -9 || true')
    abbr('mitmlc', "mitmproxy --mode=local:'Visual Studio Code.app'")
    abbr('mitmlci', "mitmproxy --mode=local:'Visual Studio Code - Insiders.app'")
    abbr('mitmlcurl', "mitmproxy --mode=local:'curl'")
    abbr('mitms', 'mitmproxy --scripts')
    abbr('mitmsave', 'mitmproxy --save-stream-file')
    abbr('lr', 'luarocks')
    abbr('lrll', 'luarocks list --local')
    abbr('lrl1', 'luarocks list --lua-version=5.1 --local')
    abbr('lrl4', 'luarocks list --lua-version=5.4 --local')
    abbr('lrl5', 'luarocks list --lua-version=5.5 --local')
    abbr('lri1', 'luarocks install --lua-version=5.1 --local')
    abbr('lri4', 'luarocks install --lua-version=5.4 --local')
    abbr('lri5', 'luarocks install --lua-version=5.5 --local')
    abbr('lrrm1', 'luarocks remove --lua-version=5.1 --local')
    abbr('lrrm4', 'luarocks remove --lua-version=5.4 --local')
    abbr('lrrm5', 'luarocks remove --lua-version=5.5 --local')
    abbr('lrs1', 'luarocks search --lua-version=5.1')
    abbr('lrs4', 'luarocks search --lua-version=5.4')
    abbr('lrs5', 'luarocks search --lua-version=5.5')
    abbr('lrshow1', 'luarocks show --lua-version=5.1')
    abbr('lrshow4', 'luarocks show --lua-version=5.4')
    abbr('lrshow5', 'luarocks show --lua-version=5.5')
    abbr('pm', 'pacman')
    abbr('pmss', "sudo pacman -Ss '^%'", cursor_marker="%")
    abbr('pm_search', "sudo pacman -Ss '^%'", cursor_marker="%")
    abbr('pmsi', 'pacman -Si')
    abbr('pm_info', 'pacman -Si')
    abbr('pms', 'sudo pacman --noconfirm -S')
    abbr('pm_install', 'sudo pacman --noconfirm -S')
    abbr('pmsu', 'sudo pacman -Syu')
    abbr('pm_update', 'sudo pacman -Syu')
    abbr('pmr', 'sudo pacman -R --recursive')
    abbr('pm_uninstall', 'sudo pacman -R --recursive')
    abbr('pmq', 'pacman -Q')
    abbr('pm_listinstalled', 'pacman -Q')
    abbr('pmqi', 'pacman -Qi')
    abbr('pmqs', 'pacman -Qs')
    abbr('pmqg', "pacman -Q | rg_grep -i '%'", cursor_marker="%")
    abbr('pmqgs', "pacman -Q | rg_grep -i '^%'", cursor_marker="%")
    abbr('pmql', 'pacman -Ql')
    abbr('pmqlt', 'pacman -Qlq % | treeify_with_icons ', cursor_marker="%")
    abbr('pm_listinstalledpkgfiles', 'pacman -Qlq % | treeify', cursor_marker="%")
    abbr('pmqo', 'pacman -Qo')
    abbr('pm_whoownsfile', 'pacman -Qo')
    abbr('pmqe', 'pacman -Q --explicit')
    abbr('pmqd', 'pacman -Q --deps')
    abbr('pm_list_explicit_installs', 'pacman -Q --explicit')
    abbr('pm_list_implicit_installs_aka_deps', 'pacman -Q --deps')
    abbr('pm_list_upgrades', 'pacman -Q --upgrades')
    abbr('pmf', 'pacman -F')
    abbr('pmfl', 'pacman -Fl')
    abbr('pmflt', 'pacman -Flq % | treeify', cursor_marker="%")
    abbr('pm_listremotepkgfiles', 'pacman -Flq % | treeify', cursor_marker="%")
    abbr('pmfy', 'sudo pacman -Fy')
    abbr('pmtree_list_installed_pkgs_that_use', 'pactree --reverse --color')
    abbr('pmtree_list_all_pkgs_used_by', 'pactree --sync --color')
    abbr('pmtree_list_all_pkgs_that_use', 'pactree --sync --reverse --color')
    abbr(re.compile('^d(\\d+)$'), abbr_from_fish_function('__pactree_depth'), position="anywhere", commands=('pactree',))
    abbr('prm', 'sudo pacman -R')
    abbr('pum', 'sudo pacman -U')
    abbr('nv', 'nvidia-%', cursor_marker="%")
    abbr('ns', 'nvidia-smi')
    abbr('nsl', 'nvidia-smi -L')
    abbr('nst', 'nvidia-smi -q -d temperature | bat -l yml')
    abbr('nsu', 'nvidia-smi -q -d utilization | bat -l yml')
    abbr('nstw', '\\$WATCH_COMMAND nvidia-smi -q -d temperature')
    abbr('nsuw', '\\$WATCH_COMMAND nvidia-smi -q -d utilization')
    abbr('nsm', 'nvidia-smi -q -d memory | bat -l yml')
    abbr('nsmw', '\\$WATCH_COMMAND nvidia-smi -q -d memory')
    abbr('nsp', 'nvidia-smi -q -d power | bat -l yml')
    abbr('nspm', '\\$WATCH_COMMAND -n 1 nvidia-smi -q -d power,memory,utilization')
    abbr('nsf', 'nvidia-smi -q -d clock | bat -l yml')
    abbr('nsdmon', 'nvidia-smi dmon')
    abbr('nspmon', 'nvidia-smi pmon')
    abbr('nswatch', '\\$WATCH_COMMAND -n 1 nvidia-smi')
    abbr('nspids', 'nvidia-smi --query-compute-apps=pid,process_name,used_memory --format=csv')
    abbr('nstopo', 'nvidia-smi topo -m')
    abbr('nsnvlink', 'nvidia-smi nvlink -s')
    abbr('nsgpu', 'nvidia-smi --query-gpu=gpu_name,gpu_bus_id,vbios_version --format=csv')
    abbr('nsall', 'nvidia-smi --query-gpu=timestamp,name,pci.bus_id,driver_version,pstate,pcie.link.gen.max,pcie.link.gen.current,temperature.gpu,utilization.gpu,utilization.memory,memory.total,memory.free,memory.used --format=csv')
    abbr('fuc', 'fish_update_completions')
    abbr('fish_from_source', abbr_from_fish_function('_fish_from_source'))
    abbr('lscpue', 'lscpu -e')
    abbr('lscpuon', 'lscpu -e --online')
    abbr('lscpuoff', 'lscpu -e --offline')
    abbr('lspcit', 'lspci -tv')
    abbr('lspcik', 'lspci -k')
    abbr('lspciu', 'lspci -k -d ::00xx')
    abbr('lspcii', 'lspci -k -d ::01xx')
    abbr('lspcin', 'lspci -k -d ::02xx')
    abbr('lspcig', 'lspci -k -d ::03xx')
    abbr('lshw', 'sudo lshw')
    abbr('lshws', 'sudo lshw -sanitize')
    abbr('lshwb', 'sudo lshw -businfo')
    abbr('lshwcd', 'sudo lshw -class display')
    abbr('lshwcn', 'sudo lshw -class network')
    abbr('lshwcs', 'sudo lshw -class storage')
    abbr('lsmodg', "sudo lsmod | rg_grep -i '%'", cursor_marker="%")
    abbr('lsmem', 'lsmem --output-all')
    abbr('lsusb', platform_abbreviation('system_profiler SPUSBDataType', 'lsusb -tv'))
    abbr('lsusbv', 'lsusb -v')
    abbr('dmesgg', "sudo dmesg | rg_grep -i '%'", cursor_marker="%")
    abbr('sp', 'system_profiler')
    abbr('sp_list_datatypes', 'system_profiler -listDataTypes')
    abbr('lsusb', platform_abbreviation('system_profiler SPUSBDataType', 'lsusb -tv'))
    abbr('lspci', 'system_profiler SPPCIDataType')
    abbr('lscpu', 'sysctl -n machdep.cpu.brand_string; sysctl -n hw.physicalcpu; sysctl -n hw.logicalcpu')
    abbr('lsblk', 'diskutil list')
    abbr('dmidecode', 'system_profiler SPHardwareDataType')
    abbr('inxi', 'system_profiler SPHardwareDataType; system_profiler SPSoftwareDataType')
    abbr('hwinfo', 'system_profiler SPHardwareDataType')
    abbr('free', 'vm_stat')
    abbr('dmesg', 'log show --predicate \'eventMessage contains "kernel"\' --info --debug --last 1m')
    abbr('lsblk_fs', 'lsblk --fs')
    abbr('lsblk_nvme', 'lsblk --nvme')
    abbr('lsblk_scsi', 'lsblk --scsi')
    abbr('lsblk_virtio', 'lsblk --virtio')
    abbr('lsblk_topology', 'lsblk --topology')
    abbr('fdisk_ls', 'sudo fdisk -l')
    abbr('fdisk_details', 'sudo fdisk -lx')
    abbr('findmnt_fstab', 'findmnt --fstab')
    abbr('findmnt_verify', 'findmnt --verify --verbose')
