"""Generated from zsh/compat_fish/gh.zsh; edit Fish/Zsh and rerun the generator."""

from wes_abbreviations import abbr

SOURCE_FUNCTIONS = ()


def register_gh_abbreviations():
    abbr('ghr', 'gh reference')
    abbr('ghh', 'gh reference')
    abbr('ghi', 'gh issue')
    abbr('ghils', 'gh issue list')
    abbr('ghis', 'gh issue list --search Q')
    abbr('ghisw', 'gh issue list --web --search Q ')
    abbr('ghiw', 'gh issue list --web')
    abbr('ghs', 'gh search')
    abbr('ghsr', 'gh search repos')
    abbr('ghsro', 'gh search repos --owner=')
    abbr('ghsi', 'gh search issues')
    abbr('ghsio', 'gh search issues --owner=')
    abbr('ghsir', 'gh search issues --repo=')
    abbr('ghsp', 'gh search prs')
    abbr('ghspo', 'gh search prs --owner=')
    abbr('ghspr', 'gh search prs --repo=')
    abbr('ghsc', 'gh search code')
    abbr('ghsco', 'gh search code --owner=')
    abbr('ghscr', 'gh search code --repo=')
    abbr('ghscof', 'gh search code --filename --owner')
    abbr('ghscm', 'gh search commits')
    abbr('ghscmo', 'gh search commits --owner=')
    abbr('ghscmr', 'gh search commits --repo=')
    abbr('ghwf', 'gh workflow')
    abbr('ghwfl', 'gh workflow list')
    abbr('ghwfr', 'gh workflow run')
    abbr('ghwfv', 'gh workflow view')
    abbr('ghwfe', 'gh workflow enable')
    abbr('ghwfd', 'gh workflow disable')
    abbr('ghrun', 'gh run')
    abbr('ghrunr', 'gh run rerun')
    abbr('ghrunl', 'gh run list')
    abbr('ghrunc', 'gh run cancel')
    abbr('ghrunrm', 'gh run delete')
    abbr('ghrunv', 'gh run view')
    abbr('ghrunw', 'gh run watch')
    abbr('ghe', 'gh extension')
    abbr('ghel', 'gh extension list')
    abbr('gheb', 'gh extension browse')
    abbr('ghes', 'gh extension search')
    abbr('ghei', 'gh extension install')
    abbr('gherm', 'gh extension remove')
    abbr('ghw', 'gh repo view --web')
    abbr('ghb', 'gh repo view --branch')
    abbr('ghwb', 'gh repo view --web --branch')
    abbr('ghv', 'gh repo view')
    abbr('ghrd', 'gh repo delete')
    abbr('ghrl', 'gh repo list --no-archived --limit 1000')
    abbr('ghcoe', 'gh copilot explain')
    abbr('ghcos', 'gh copilot suggest -t shell')
