"""Git abbreviations generated from fish/load_last_interactive_only/git.fish."""

from __future__ import annotations

import re

from wes_abbreviations import abbr
from wes_fish_bridge import fish_function


def _fish_abbreviation(function_name):
    def expand(context, _match):
        return fish_function(function_name, context.token)

    return expand


def register_git_abbreviations():
    abbr("-W", "--function-context", commands=("git", "diff"))
    abbr('man_gitrevisions', 'man gitrevisions')
    abbr(re.compile('reflog\\d+'), _fish_abbreviation('_abbr_expand_reflog_d'), position="anywhere")
    abbr('commit_with_message', ':/%', position="anywhere", cursor_marker="%")
    abbr('gsts', 'git status -s')
    abbr('gstb', 'git status -sb')
    abbr('gstu', 'git status --untracked-files')
    abbr('gsti', 'git status --ignored .')
    abbr('gstiv', 'git status --ignored --untracked-files --short ".%" | rg_grep -i -v "node_modules|\\.venv/|\\.rag/|__pycache__|DS_Store|\\.pytest_cache/|/bin/|/obj/|/target/|iterm2env/|egg-info/|dist/"', cursor_marker="%")
    abbr('gstiv_all', 'git status --ignored --untracked-files --short ".%" | rg_grep -i -v "node_modules|\\.venv/|\\.rag/|__pycache__|DS_Store|\\.pytest_cache/|/bin/|/obj/|/target/|iterm2env/|egg-info/|dist/|.*\\.(png|bmp|jpg|svg)\\$"', cursor_marker="%")
    abbr('grhh', 'git reset --hard HEAD')
    abbr('grh_undo_amend_commit', 'git reset --hard HEAD@{1}')
    abbr('grsh', 'git reset --soft HEAD~1')
    abbr('groh', 'git reset --hard ORIG_HEAD')
    abbr('gclean', 'git clean -d --dry-run')
    abbr('gcleani', 'git clean -d --interactive')
    abbr('gcleanx', 'git clean -d -x --dry-run')
    abbr('gpristine', 'git reset --hard && git clean -dffx')
    abbr('ga', 'git add')
    abbr('ga.', 'git add .')
    abbr('ga..', 'git add ..')
    abbr('gav', 'git add --verbose')
    abbr('gaa', 'git add --all')
    abbr('gaaa', 'git add --all')
    abbr('gau', 'git add --update')
    abbr('gap', 'git add --patch')
    abbr('gai', 'git add --interactive')
    abbr('gb', 'git branch')
    abbr('gbv', 'git branch -vv')
    abbr('gba', 'git branch --all -vv')
    abbr('gbr', 'git branch --remotes -vv')
    abbr('gbd', 'git branch --delete')
    abbr('gbD', 'git branch -D')
    abbr('gbdf', 'git branch --delete --force')
    abbr('gbl', 'git blame -b -w')
    abbr('review', "git commit -a -m 'review'")
    abbr('notes', "git commit -a -m 'notes'")
    abbr('gc', 'GIT_EDITOR=git-commit-with-function-context git commit')
    abbr('gca', 'GIT_EDITOR=git-commit-with-function-context git commit -a')
    abbr('gc!', 'GIT_EDITOR=git-commit-with-function-context git commit --amend')
    abbr('gcn!', 'git commit --no-edit --amend')
    abbr('gca!', 'GIT_EDITOR=git-commit-with-function-context git commit -a --amend')
    abbr('gcan!', 'git commit -a --no-edit --amend')
    abbr('gco', 'git checkout')
    abbr('gcom', 'git checkout master')
    abbr('gcop', 'git restore --patch')
    abbr('gcob', 'git checkout -b')
    abbr('gconf', 'grc git config --list --show-origin --show-scope')
    abbr('gnoconf', 'env GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null grc git config --list --show-origin --show-scope')
    abbr('gnoconf_export', 'export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null')
    abbr('gcl', 'git clone --recurse-submodules')
    abbr('gcl_no_lfs', 'GIT_LFS_SKIP_SMUDGE=1 git clone --recurse-submodules')
    abbr('wcl_no_lfs', 'GIT_LFS_SKIP_SMUDGE=1 wcl')
    abbr('gf', 'git fetch')
    abbr('gfa', 'git fetch --all --prune --jobs=10')
    abbr('gp', 'git push')
    abbr('gpsup', 'git push --set-upstream origin $(git_current_branch)')
    abbr('gpd', 'git push --dry-run')
    abbr('gpf', 'git push --force')
    abbr('gpl', 'git pull')
    abbr('gplas', 'git pull --autostash')
    abbr('gplr', 'git pull --recurse-submodules')
    abbr('gr', 'git remote')
    abbr('grv', 'git remote -v')
    abbr('gra', 'git remote add')
    abbr('grao', 'git remote add origin')
    abbr('grau', 'git remote add upstream')
    abbr('grsuo', 'git remote set-url origin')
    abbr('grsuu', 'git remote set-url upstream')
    abbr('grup', 'git remote update')
    abbr('gm', 'git merge')
    abbr('gma', 'git merge --abort')
    abbr('gmc', 'git merge --continue')
    abbr('gmff', 'git merge --ff-only')
    abbr(re.compile('grev\\d+'), _fish_abbreviation('_abbr_expand_grev_d'))
    abbr('grm', 'git rm')
    abbr('grmc', 'git rm --cached')
    abbr('grst', 'git restore --staged')
    abbr('grstp', 'git restore --staged --patch')
    abbr('grstr', 'git restore --staged $(_repo_root)')
    abbr('grp', 'git restore --patch')
    abbr('grss', 'git restore --source')
    abbr('grevp_upstream', 'git rev-parse @{upstream}')
    abbr('grevp_upstream_symbolic', 'git rev-parse --symbolic-full-name @{upstream}')
    abbr('grevp_push', 'git rev-parse @{push}')
    abbr('grevp_push_symbolic', 'git rev-parse --symbolic-full-name @{push}')
    abbr('gsh', 'git show')
    abbr('gsh_file', 'git --no-pager show HEAD:%', cursor_marker="%")
    abbr('gsps', 'git show --pretty=short --show-signature')
    abbr('gcat', 'git cat-file -p HEAD:%', cursor_marker="%")
    abbr('gsm', 'git submodule')
    abbr('gsma', 'git submodule add --branch master')
    abbr('gsmd', 'git submodule deinit')
    abbr('gsmf', 'git submodule foreach')
    abbr('gsmfgl', 'git submodule foreach --recursive git pull')
    abbr('gsme', 'git submodule foreach')
    abbr('gsmi', 'git submodule init')
    abbr('gsmu', 'git submodule update --remote --recursive')
    abbr('gsmst', 'git submodule status --recursive')
    abbr('gsw', 'git switch')
    abbr('gswc', 'git switch -c')
    abbr('gts', 'git tag -s')
    abbr('gtv', 'git tag | sort -V')
    abbr('gassume', 'git update-index --assume-unchanged')
    abbr('gassumeun', 'git update-index --no-assume-unchanged')
    abbr('gassumels', 'git ls-files -v | rg_grep ^h')
    abbr('gd', 'git diff')
    abbr('gdic', 'git-icdiff HEAD')
    abbr('gdu', 'git -c delta.side-by-side=false diff')
    abbr(re.compile('gd[u]*\\d+'), _fish_abbreviation('gdX'))
    abbr(re.compile('gdic\\d+'), _fish_abbreviation('gdX'))
    abbr('gd_summary', 'git diff --summary')
    abbr('gd_worktree', 'git diff')
    abbr('gds', 'git diff --staged')
    abbr('gdics', 'git-icdiff --staged')
    abbr('gds_summary', 'git diff --staged --summary')
    abbr('gd_index', 'git diff --staged')
    abbr('git_diff_two_files', 'git diff --no-index')
    abbr('gdni', 'git diff --no-index')
    abbr('git_diff_two_dirs', "git diff --no-index __dir1__ __dir2__ '*foo*'")
    abbr('gd_is_worktree_clean', 'git diff --quiet')
    abbr('gd_is_index_clean', 'git diff --staged --quiet')
    abbr('gdlf', 'git diff-tree -r HEAD~1 HEAD')
    abbr('dsf', 'diff-so-fancy')
    abbr('lfs', 'git lfs')
    abbr('lfsi', 'git lfs install')
    abbr('lfsls', 'git lfs ls-files')
    abbr('lfsm', 'git lfs migrate')
    abbr('lfspr', 'git lfs prune')
    abbr('lfsst', 'git lfs status')
    abbr('lfst', "git lfs track '*.EXT'")
    abbr('lfsup', 'git lfs update')
    abbr('lfsut', "git lfs untrack '*.EXT'")
    abbr('lfsv', 'git lfs version')
    abbr('grvcp', _fish_abbreviation('_grvcp'))
    abbr('gcmsg', 'git commit -m "%"', cursor_marker="%")
    abbr('gcam', 'git commit -a -m "%"', cursor_marker="%")
    abbr('gptoss', '--author "gptoss120b<wes.mcclure+gptoss120b@gmail.com>"', commands=('git',))
    abbr('qwen3', '--author "qwen3.6-35b-a3b<wes.mcclure+qwen3.6-35b-a3b@gmail.com>"', commands=('git',))
    abbr('agentworld', '--author "qwen-agentworld-35b-a3b<wes.mcclure+qwen-agentworld-35b-a3b@gmail.com>"', commands=('git',))
    abbr('codex', '--author "codex-gpt6<wes.mcclure+codex-gpt6@gmail.com>"', commands=('git',))
    abbr('deepseek', '--author "deepseek-v4-flash<wes.mcclure+deepseek-v4-flash@gmail.com>"', commands=('git',))
    abbr('muse', '--author "muse-glimmer-30b-dspark<wes.mcclure+muse-glimmer-30b-dspark@gmail.com>"', commands=('git',))
    abbr('amend_n_gptoss', 'GIT_SEQUENCE_EDITOR=true git rebase -i --exec "git commit --amend --no-edit --author \\"gptoss120b<wes.mcclure+gptoss120b@gmail.com>\\"" HEAD~%', cursor_marker="%")
    abbr('amend_n_qwen3', 'GIT_SEQUENCE_EDITOR=true git rebase -i --exec "git commit --amend --no-edit --author \\"qwen3.6-35b-a3b<wes.mcclure+qwen3.6-35b-a3b@gmail.com>\\"" HEAD~%', cursor_marker="%")
    abbr('amend_n_agentworld', 'GIT_SEQUENCE_EDITOR=true git rebase -i --exec "git commit --amend --no-edit --author \\"qwen-agentworld-35b-a3b<wes.mcclure+qwen-agentworld-35b-a3b@gmail.com>\\"" HEAD~%', cursor_marker="%")
    abbr('amend_n_codex', 'GIT_SEQUENCE_EDITOR=true git rebase -i --exec "git commit --amend --no-edit --author \\"codex-gpt5<wes.mcclure+codex-gpt5@gmail.com>\\"" HEAD~%', cursor_marker="%")
    abbr('amend_n_deepseek', 'GIT_SEQUENCE_EDITOR=true git rebase -i --exec "git commit --amend --no-edit --author \\"deepseek-v4-flash<wes.mcclure+deepseek-v4-flash@gmail.com>\\"" HEAD~%', cursor_marker="%")
    abbr('amend_n_muse', 'GIT_SEQUENCE_EDITOR=true git rebase -i --exec "git commit --amend --no-edit --author \\"muse-glimmer-30b-dspark<wes.mcclure+muse-glimmer-30b-dspark@gmail.com>\\"" HEAD~%', cursor_marker="%")
    abbr('amend_last_msg', 'git commit --amend -m "%"', cursor_marker="%")
    abbr('yolo', 'git commit --all -m "%" && git push', cursor_marker="%")
    abbr(re.compile('gptf?\\d*f?'), _fish_abbreviation('_abbr_git_push_up_to'), cursor_marker="%")
    abbr('grl', 'git reflog --pretty=reflog')
    abbr('grla', 'git reflog --all --pretty=reflog')
    abbr('gl', 'git log --color=always | line_numbers')
    abbr('glemails', 'git log --pretty=names')
    abbr('glnames', 'git log --pretty=names')
    abbr(re.compile('gl\\d+'), _fish_abbreviation('glX'))
    abbr(re.compile('g\\d+'), _fish_abbreviation('glX'))
    abbr('gst', 'git status')
    abbr('gstl', 'git status && echo && git_unpushed_commits')
    abbr('glo', 'git_unpushed_commits')
    abbr('gup', 'git_unpushed_commits')
    abbr('gout', 'git_unpushed_commits')
    abbr('gin', 'git_unpulled_commits')
    abbr('glp', 'git log --patch')
    abbr('glpf', 'git log --pretty=full --patch')
    abbr(re.compile('glpf?\\d+'), _fish_abbreviation('glp_x'))
    abbr('gls', "git log --stat 'HEAD@{push}..HEAD'")
    abbr('glsf', "git log --pretty=full --stat 'HEAD@{push}..HEAD'")
    abbr(re.compile('gls[f]{0,1}\\d+'), _fish_abbreviation('glsX'))
    abbr('glg', "git log --graph 'HEAD@{push}~1..HEAD'")
    abbr('ggsup', 'git branch --set-upstream-to=origin/$(git_current_branch)')
    abbr('git_delta_copyable', 'git -c delta.side-by-side=false -c delta.line-numbers=false')
    abbr('git_delta_side_by_side', 'git -c delta.side-by-side=true')
    abbr('git_delta_unified', 'git -c delta.side-by-side=false')
    abbr('git_delta_no_line_numbers', 'git -c delta.line-numbers=false')
    abbr('git_ignore_space_changes', 'git diff --ignore-space-change')
    abbr('git_ignore_all_space', 'git diff --ignore-all-space')
    abbr('gdlc', 'git log --patch HEAD~1..HEAD')
    abbr('gdiclc', 'git-icdiff HEAD~1..HEAD')
    abbr('gdlcu', 'git -c delta.side-by-side=false log --patch HEAD~2..HEAD')
    abbr(re.compile('gdlc[u]?\\d+'), _fish_abbreviation('gdlcX'))
    abbr(re.compile('gdiclc\\d+'), _fish_abbreviation('gdlcX'))
    abbr('gd_stat', "git diff --stat 'HEAD@{push}..HEAD'")
    abbr('glgrep', 'git log --grep="%"', cursor_marker="%")
    abbr('gd_patch', 'git --no-pager diff --no-color')
    abbr('rr', '_repo_root')
    abbr('gwt', 'git worktree')
    abbr('gwtls', 'git worktree list')
    abbr('gwta', 'git worktree add')
    abbr('gwtab', 'git worktree add -b')
    abbr('gwtrm', 'git worktree remove')
    abbr('gwtm', 'git worktree move')
    abbr('grb', 'git rebase')
    abbr('grba', 'git rebase --abort')
    abbr('grbc', 'git rebase --continue')
    abbr('grbs', 'git rebase --skip')
    abbr('grbi', 'git rebase -i')
    abbr('grbias', 'git rebase -i --autostash')
    abbr(re.compile('grbi\\d+'), _fish_abbreviation('_abbr_expand_grbi_d'))
    abbr('gstash', 'git stash')
    abbr('git_stash_list', 'git stash list --pretty=stash-list')
    abbr('git_stash_show', 'git stash show --text 0')
    abbr('git_stash_drop', 'git stash drop 0')
    abbr('git_stash_pop', 'git stash pop 0')
    abbr('git_stash_apply', 'git stash apply')
    abbr('git_stash_branch', 'git stash branch')
    abbr('git_stash_patch', 'git stash push --patch --no-keep-index')
    abbr(re.compile('gap\\d*'), _fish_abbreviation('gapX'))
    abbr('git_stash_push', 'git stash push --message "%"', cursor_marker="%")
    abbr('git_stash_save', 'git stash push --message "%"', cursor_marker="%")
    abbr('git_stash_clear', 'git stash clear')
    abbr('git_archive_tgz', 'git archive --format=tgz --output repo.tgz HEAD')
    abbr('git_archive_zip', 'git archive --format=zip --output repo.zip HEAD')
    abbr('git_archive_everything', 'git bundle create repo.bundle --all')
    abbr('gg', "git grep -Ee '%' $(git rev-list --all)", cursor_marker="%")
    abbr('ggc', "git grep -C10 -Ee '%' $(git rev-list --all)", cursor_marker="%")
    abbr('ggf', "git grep --function-context -Ee '%' $(git rev-list --all)", cursor_marker="%")
