"""Generated from zsh/compat_fish/hashicorp.zsh."""

from __future__ import annotations

from wes_abbreviations import abbr


def register_hashicorp_abbreviations():
    abbr('pa', 'packer')
    abbr('pai', 'packer init .')
    abbr('pav', 'packer validate .')
    abbr('paf', 'packer fmt .')
    abbr('pab', 'packer build .')
    abbr('v', 'vagrant')
    abbr('vlsc', 'vagrant list-commands')
    abbr('vi', 'vagrant init --minimal')
    abbr('vv', 'vagrant validate')
    abbr('vc', 'vagrant cloud')
    abbr('vcs', 'vagrant cloud search')
    abbr('vcb', 'vagrant cloud box show')
    abbr('vb', 'vagrant box')
    abbr('vbls', 'vagrant box list -i')
    abbr('vba', 'vagrant box add')
    abbr('vbo', 'vagrant box outdated')
    abbr('vbog', 'vagrant box outdated --global')
    abbr('vbu', 'vagrant box update')
    abbr('vbub', 'vagrant box update --box')
    abbr('vbpr', 'vagrant box prune --dry-run')
    abbr('vbrm', 'vagrant box remove')
    abbr('vbrep', 'vagrant box repackage')
    abbr('vpack', 'vagrant package --base ')
    abbr('vst', 'vagrant status')
    abbr('vgst', 'vagrant global-status --prune')
    abbr('vu', 'vagrant up')
    abbr('vuv', 'vagrant up --provider=virtualbox')
    abbr('vup', 'vagrant up --provider=parallels')
    abbr('vuh', 'vagrant up --provider=hyperv')
    abbr('vpv', 'vagrant provision')
    abbr('vh', 'vagrant halt')
    abbr('vhf', 'vagrant halt --force')
    abbr('vrl', 'vagrant reload')
    abbr('vrlp', 'vagrant reload --provision')
    abbr('vsp', 'vagrant suspend')
    abbr('vspg', 'vagrant suspend --all-global')
    abbr('vrs', 'vagrant resume')
    abbr('vd', 'vagrant destroy')
    abbr('vdf', 'vagrant destroy -f')
    abbr('vp', 'vagrant plugin')
    abbr('vpls', 'vagrant plugin list')
    abbr('vpi', 'vagrant plugin install')
    abbr('vprm', 'vagrant plugin uninstall')
    abbr('vpupdate', 'vagrant plugin update')
    abbr('vs', 'vagrant ssh')
    abbr('vsc', 'vagrant ssh-config')
    abbr('vscmd', 'vagrant ssh --command')
    abbr('vsn', 'vagrant snapshot')
    abbr('vsnls', 'vagrant snapshot list')
    abbr('vsns', 'vagrant snapshot save')
    abbr('vsnr', 'vagrant snapshot restore')
    abbr('vsnrm', 'vagrant snapshot delete')
    abbr('vsnpu', 'vagrant snapshot push')
    abbr('vsnpo', 'vagrant snapshot pop')
