"""Cloud Ai abbreviations generated from Fish cloud-ai-specific.fish."""

from __future__ import annotations

import re

from wes_abbreviations import abbr
from wes_fish_migration import (
    abbr_from_fish_function,
)


FISH_FUNCTIONS = (
    'actw_expanded',
    'rg_cached_models',
    'ols_qwen_debug',
    'ols_qwen',
    'cd2',
    'abbr_agg',
    'commands_log_executable_mode',
    'commands_log_shell_mode',
    'trash_n_tail',
    '_taild',
    'rebuild_llama_cpp',
    'build_llama_cpp',
    'test_vllm_v1_completions_streaming',
    'test_vllm_v1_completions',
    'test_vllm_v1_completions_raw_text',
)


def register_cloud_ai_abbreviations():
    abbr('actw', abbr_from_fish_function('actw_expanded'))
    abbr('azal', 'az account list --output table')
    abbr('azall', 'az account list-locations --output table')
    abbr('azrl', 'az resource list --output table')
    abbr('azrs', 'az resource show --output table')
    abbr('azgl', 'az group list --output table')
    abbr('azwl', 'az webapp list --output table')
    abbr('azasl', 'az appservice plan list --output table')
    abbr('hfc', 'hf cache')
    abbr('hfcls', 'hf cache ls --no-truncate --revisions')
    abbr('hfcpr', 'hf cache prune')
    abbr('hfcrm', 'hf cache rm')
    abbr('hfcv', 'hf cache verify')
    abbr('hfc_downloadInProgress', 'fd .downloadInProgress ~/.cache/huggingface/')
    abbr('hfml', 'hf models ls')
    abbr('hfmls', 'hf models ls --search')
    abbr('hfmlsa', 'hf models ls --limit 30 --author')
    abbr('hfmls_ggml_org', 'hf models ls --limit 30 --author ggml-org')
    abbr('hfmls_ggml_org_qwen36', 'hf models ls --limit 30 --author ggml-org --search qwen3.6')
    abbr('hfmls_ggml_org_qwen35', 'hf models ls --limit 30 --author ggml-org --search qwen3.5')
    abbr('hfmls_qwen', 'hf models ls --limit 30 --author Qwen')
    abbr('hfmls_qwen_qwen36', 'hf models ls --limit 30 --author Qwen --search qwen3.6')
    abbr('hfmls_qwen_qwen35', 'hf models ls --limit 30 --author Qwen --search qwen3.5')
    abbr('hfmi', 'hf models info')
    abbr('hfdl', 'hf datasets ls')
    abbr('hfdls', 'hf datasets ls --search')
    abbr('hfdla', 'hf datasets ls --author')
    abbr('hfdinfo', 'hf datasets info')
    abbr('hfcols', 'hf collections ls --owner')
    abbr('hfcols_ggml_org', 'hf collections ls --owner ggml-org')
    abbr('hfcols_qwen', 'hf collections ls --owner Qwen')
    abbr('hfcoi', 'hf collections info % | jq ".items | .[] | [ .item_type, .item_id ] " --compact-output')
    abbr('hfsp', 'hf skills preview')
    abbr('lsh', 'llama-server --help')
    abbr('lslsd', 'llama-server --list-devices')
    abbr('lsv', 'llama-server --version')
    abbr('lsc', 'llama-server --cache-list')
    abbr('ls_test_completions_stream', "http paxy.lan:8016/completions stream:=true max_tokens:=10 prompt='what is 11*2'")
    abbr('ls_test_completions_sync', "http paxy.lan:8016/completions stream:=false max_tokens:=100 prompt='what is 11*2'")
    abbr('ls_test_chat_stream', 'http paxy.lan:8016/chat/completions verbose:=true stream:=true max_tokens:=11 \'messages:=[ {"role": "user", "content": "what is 11*2"} ]\'')
    abbr('ls_test_chat_sync', 'http paxy.lan:8016/chat/completions verbose:=true stream:=false max_tokens:=100 \'messages:=[ {"role": "user", "content": "what is 11*2"} ]\'')
    abbr('olc', 'ollama create')
    abbr('olcp', 'ollama cp')
    abbr('ole', 'export OLLAMA_HOST=ollama.lan:11434')
    abbr('olh', 'ollama help')
    abbr('ollnaked', 'grc ollama list')
    abbr('oll', 'ollama list | awk \'{OFS="\\t" } /%/ { print $3$4,$1,$2,$5" "$6" "$7" "$8" "$9 }\' | sort -h | column -t | grcat conf.ollama_list', cursor_marker="%")
    abbr('ollqwen3coder', 'grc ollama list qwen3-coder')
    abbr('ollqwen25coder', 'grc ollama list qwen2.5-coder')
    abbr('ollqwen25', 'grc ollama list qwen2.5:')
    abbr('ollqwen3', 'grc ollama list qwen3:')
    abbr('ollgptoss', 'grc ollama list gpt-oss')
    abbr('olp', 'ollama pull')
    abbr('olps', 'ollama ps')
    abbr('olpush', 'ollama push')
    abbr('olr', 'ollama run --verbose')
    abbr('olrm', 'ollama rm')
    abbr('olsl', 'OLLAMA_NUM_PARALLEL=1 ollama serve 2>&1 | bat -pp -l log')
    abbr('olsld', 'OLLAMA_NUM_PARALLEL=1 OLLAMA_DEBUG=2 ollama serve 2>&1 | bat -pp -l log')
    abbr('olsg', "OLLAMA_NUM_PARALLEL=1 OLLAMA_HOST='http://0.0.0.0:11434' ollama serve 2>&1 | bat -pp -l log")
    abbr('olsgd', "OLLAMA_NUM_PARALLEL=1 OLLAMA_DEBUG=2 OLLAMA_HOST='http://0.0.0.0:11434' ollama serve 2>&1 | bat -pp -l log")
    abbr('olsq', 'ols_qwen')
    abbr('olsqd', 'ols_qwen_debug')
    abbr('olshow', 'grc ollama show')
    abbr('olshow_template', 'ollama show --template % | bat -l go', cursor_marker="%")
    abbr('olshow_modelfile', 'ollama show --modelfile % | bat -l Dockerfile', cursor_marker="%")
    abbr('anr', 'asciinema rec --overwrite test.cast')
    abbr('anp', 'asciinema play')
    abbr('anu', 'asciinema upload')
    abbr('anc', 'asciinema cat')
    abbr('aggo', abbr_from_fish_function('abbr_agg'))
    abbr('vllms', 'vllm serve')
    abbr('vllmb', 'vllm bench')
    abbr('vllmc', 'vllm chat')
    abbr('vllmg', 'vllm complete')
    abbr('tailf', 'tail -F -n 1000')
    abbr('tailF', 'tail -F -n 1000')
    abbr('tailn', 'tail -n 1000')
    abbr('tailr', 'tail -r')
    abbr('tt', 'trash_n_tail')
    abbr('tt_xonsh', 'trash_n_tail -F ~/.local/state/xonsh/xonsh.log')
    abbr('tt_devtools_universal', 'trash_n_tail ~/.local/share/devtools/universal.log')
    abbr('tt_devtools_hammerspoons', 'trash_n_tail ~/.local/share/devtools/hammerspoons.log')
    abbr('tt_devtools_launcher', 'trash_n_tail ~/.local/share/devtools/launcher.log')
    abbr('tt_mcp_server_commands', 'tail -F ~/.local/state/mcp-server-commands/commands.log')
    abbr('tail_mcp_server_commands', 'tail -F ~/.local/state/mcp-server-commands/commands.log')
    abbr('commands_log_review', 'commands_log_executable_mode; commands_log_shell_mode')
    abbr('tt_agents_mcp_server', 'tail -F ~/.local/state/mcp-servers/agent.log')
    abbr('tt_ask_lang_server', 'trash_n_tail ~/.local/state/ask-openai/language.server.log')
    abbr('tail_ask_lang_server', 'tail -F ~/.local/state/ask-openai/language.server.log')
    abbr('tt_nvim_lsp_log', 'trash_n_tail ~/.local/state/nvim/lsp.log')
    abbr('tail_nvim_lsp_log', 'tail -F ~/.local/state/nvim/lsp.log')
    abbr('tt_streamdeck_wes', 'trash_n_tail ~/.hammerspoon/logs/streamdeck_keyboardmaestro_runner.log')
    abbr('tail_streamdeck_wes', 'tail -F ~/.hammerspoon/logs/streamdeck_keyboardmaestro_runner.log')
    abbr('tail_hardtime_logs', 'cat ~/.local/state/nvim/hardtime.nvim.log | cut -c34- | sort | uniq -c | sort')
    abbr(re.compile('tail\\d+'), abbr_from_fish_function('_taild'))
    abbr('yapfs', 'yapf --style-help')
    abbr('sh', '--style-help', position="anywhere", commands=('yapf',))
    abbr('wscatc', 'wscat --connect -L --slash --show-ping-pong ws://localhost:8000')
    abbr('wscatl', 'wscat --listen 8000')
    abbr('wscat_echo_org', 'wscat --connect -L --slash --show-ping-pong ws://echo.websocket.org')
    abbr('una', 'uname -a')
    abbr('hs', 'hs -C')
    abbr('hs_interactive', 'hs -C')
    abbr('hsq', 'hs -q')
    abbr('hs_clone_from_console', 'hs -C')
    abbr('hs_clone_to_console', 'hs -P')
    abbr('hsc', 'hs -c')
    abbr('hs_open_console', "hs -c 'hs.openConsole()'")
    abbr('hs_reload', "hs -c 'hs.openConsole(); hs.reload(); hs.console.clearConsole()'")
    abbr('hs_clear_console', "hs -c 'hs.console.clearConsole()'")
    abbr('hscq', 'hs -c -q')
    abbr('ct', 'ctags')
    abbr('ctags_stdout_only_lua', 'ctags --languages=lua -f -')
    abbr('ctl', 'ctags --list-%', cursor_marker="%")
    abbr('ctle', 'ctags --list-excludes')
    abbr('ctll', 'ctags --list-languages')
    abbr('ctlf', 'ctags --list-fields')
    abbr('ctlx', 'ctags --list-extras')
    abbr('ctags_stdout', 'ctags -f -')
    abbr('ctags_list_not_files', "cat tags  | sort | uniq | rg_grep --invert-match '\\.(zsh|lua|py|rs|c|md|json|vim|plist|js|ps1)' | bat -l csv")
    abbr('psse', "| sed -E 's/^[^{]*//' | jq", position="anywhere")
    abbr('pssec', "| sed -E 's/^[^{]*//' | jq --compact-output", position="anywhere")
    abbr('pdata', "| rg_grep -v ':data' | sed -E 's/^[^{]*//' | jq", position="anywhere")
    abbr('pb_copy_sse', "pbpaste | sed -E 's/^[^{]*//' | jq | pbcopy")
    abbr('pbsse', "pbpaste | sed -E 's/^[^{]*//' | jq")
    abbr('pbssec', "pbpaste | sed -E 's/^[^{]*//' | jq --compact-output")
    abbr('pbsse_verbose_prompt', "pbpaste | sed -E 's/^[^{]*//' | jq '.__verbose.prompt' -r")
    abbr('pbsse_verbose_prompt_harmony', "pbpaste | sed -E 's/^[^{]*//' | jq '.__verbose.prompt' -r | tree-sitter highlight --scope source.harmony")
    abbr('pbsse_verbose_content', "pbpaste | sed -E 's/^[^{]*//' | jq '.__verbose.content' -r")
    abbr('pbsse_verbose_raw_response', "pbpaste | sed -E 's/^[^{]*//' | jq '.__verbose.content' -r")
    abbr('pbsse1', "pbpaste | sed -E 's/^[^{]*//' | jq > input-messages.json")
    abbr('pbsse2', "pbpaste | sed -E 's/^[^{]*//' | jq > input-rendered-prompt.json")
    abbr('pbsse3', "pbpaste | sed -E 's/^[^{]*//' | jq > output-parsed-message.json")
    abbr('pbssetrace', 'view_trace (pbpaste | string replace --regex "[^{]*" "" | psub)')
    abbr('pbsse4', "pbpaste | string replace --regex '^\\w\\w\\w \\d\\d \\d\\d:\\d\\d:\\d\\d \\w+ llama-server\\[\\d+\\]: ' '' | string replace 'Parsing input with format GPT-OSS: ' '' > output-raw.harmony")
    abbr('llama_server_current_chat_template', 'curl paxy:8013/props | jq .chat_template --raw-output')
    abbr('-S', '--sort-keys', position="anywhere", commands=('jq',))
    abbr('-C', '--color-output', position="anywhere", commands=('jq',))
    abbr('-c', '--compact-output', position="anywhere", commands=('jq',))
    abbr('-r', '--raw-output', position="anywhere", commands=('jq',))
    abbr('-j', '--join-output', position="anywhere", commands=('jq',))
    abbr('jqk', 'jq keys')
    abbr('sort_keys', 'jq --sort-keys', position="anywhere", commands=('jq',))
    abbr('not_null', '| select(.)', position="anywhere", commands=('jq',))
    abbr('yqy', 'yq --yaml-output')
    abbr('-y', '--yaml-output', position="anywhere", commands=('yq',))
    abbr('-c', '--compact-output', position="anywhere", commands=('yq',))
    abbr('-r', '--raw-output', position="anywhere", commands=('yq',))
    abbr('clm', 'ANTHROPIC_BASE_URL="http://ask.lan:8012" claude --model Qwen/Qwen3-Coder-Next-GGUF:Q8_0')
    abbr('clr', 'claude --resume')
    abbr('cld', 'claude --dangerously-skip-permissions')
    abbr('-h', '--help', position="anywhere", commands=('nix',))
    abbr('nixh', 'nix --help')
    abbr('nixpls', 'nix profile list')
