require("config.macros.screenpal.co")
local TestTimer = require("config.macros.screenpal.test_timing")

describe("cos", function()
    it("test w/o run_async because test already has a coroutine", function()
        local timer = TestTimer:new(250)
        sleep_ms(250)
        timer:stop()
    end)

    it("test run_async works too, bypasses creating coroutine", function()
        run_async(function()
            local timer = TestTimer:new(250)
            sleep_ms(250)
            timer:stop()
        end)
    end)
end)
