ealias mza='man zshall'
ealias mzr='man zshroadmap'
ealias mzm='man zshmisc'

ealias mzb='man zshbuiltins'
ealias mze='man zshexpn'
ealias mzo='man zshoptions'
ealias mzp='man zshparam'
ealias mzle='man zshzle'
ealias mzcw='man zshcompwid'
ealias mzcs='man zshcompsys'
ealias mzcc='man zshcompctl'
ealias mzlm='man zshmodules'
ealias mzcal='man zshcalsys'
#ealias mztcp='man zshtcpsys'
#ealias mzcal='man zshzftpsys'
#ealias mzc='man zshcontrib'
