-- what I care about:
--  complete require("foo.<TAB> to correct paths
--  F12 go to files
--  see my coc keymaps
--    gd/gr goto def, usages, etc
--
--  enter to accept, tab is reserved for copilot du jour plugin
