#!/usr/bin/env python3
"""Generate Fish's shared misc abbreviations from the Xonsh definitions."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / ".config/xonsh/lib"))

from wes_abbreviations import reset_registry  # noqa: E402
from wes_misc_abbreviations import register_misc_abbreviations  # noqa: E402


TARGET = ROOT / "fish/generated/misc-abbreviations.fish"

# Xonsh and Fish spell command substitution differently. Keep Fish's quoted
# path substitutions so a repository path containing spaces stays one argument.
FISH_REPLACEMENTS = {
    "cdr": 'cd "$(_repo_root)"',
    "orr": 'open "$(_repo_root)"',
    "cr": 'code "$(_repo_root)"',
    "cir": 'code-insiders "$(_repo_root)"',
    "csr": 'cursor "$(_repo_root)"',
}
FISH_ONLY = {"pPATH"}


def fish_quote(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"

# !!! THIS IS A FIRST XONSH native config that is migrated to fish

def render() -> str:
    registry = reset_registry()
    register_misc_abbreviations()
    lines = [
        "# Generated by xonsh/generate_misc_fish_abbreviations.py; edit wes_misc_abbreviations.py instead.",
    ]
    for entry in registry.abbreviations:
        if entry.trigger in FISH_ONLY:
            continue
        if not isinstance(entry.trigger, str) or not isinstance(entry.replacement, str):
            raise ValueError(f"Cannot generate Fish abbreviation for {entry.trigger!r}")
        if entry.position not in ("command", "anywhere") or len(entry.commands) > 1:
            raise ValueError(f"Unsupported Fish abbreviation options for {entry.trigger!r}")
        if entry.cursor_marker not in (None, "%"):
            raise ValueError(f"Unsupported Fish cursor marker for {entry.trigger!r}")
        replacement = FISH_REPLACEMENTS.get(entry.trigger, entry.replacement)
        # Fish's --set-cursor without an embedded marker puts the cursor at
        # the end. Xonsh represents that same position with a trailing `%`.
        if entry.cursor_marker and replacement.endswith(entry.cursor_marker):
            replacement = replacement[: -len(entry.cursor_marker)]
        parts = ["abbr --add"]
        if entry.commands:
            parts.extend(("--command", fish_quote(entry.commands[0])))
        elif entry.position == "anywhere":
            parts.append("--position anywhere")
        if entry.cursor_marker:
            parts.append("--set-cursor")
        parts.extend(("--", fish_quote(entry.trigger), fish_quote(replacement)))
        lines.append(" ".join(parts))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(render())
