#!/usr/bin/env fish

log_ --bold "hook[$(status basename)] $argv"

# $1 == amend/rebase
# post-rewrite is called for amend and rebase
if test $argv[1] = amend
    # amend will also trigger post-commit
    echo "  skipping '$argv[1]'"
    exit
end

set parent_dir (dirname (status current-filename))
"$parent_dir/core.fish"
