# resolve path to this script so I can import others nearby
my_loc=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

# * uncomment for xtrace-ing
# export PS1="$ "
# unset PROMPT_COMMAND # remove default for xtrace, when also comment out the return here:
# return

for script in "$my_loc/startup/"*; do
    source "$script"
done
